In [1]:
import numpy as np

In [2]:
x = np.arange(1,20)

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
x[5]

6

In [5]:
x[-1]

19

In [6]:
x[:10]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
x[2:8]

array([3, 4, 5, 6, 7, 8])

In [8]:
x[10:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
x[-14:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
y = x[5:10] = 30  #assign vale 30 in index 5 to 10


In [11]:
y

30

In [12]:
x

array([ 1,  2,  3,  4,  5, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [13]:
y = x.copy()  #copy x array to y

In [14]:
y


array([ 1,  2,  3,  4,  5, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [15]:
y[0:4] = 0

In [16]:
y

array([ 0,  0,  0,  0,  5, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
x

array([ 1,  2,  3,  4,  5, 30, 30, 30, 30, 30, 11, 12, 13, 14, 15, 16, 17,
       18, 19])