In [1]:
import numpy as np

In [2]:
x = [1,2,3,4,5]

In [3]:
y = [[1,2,3],[4,5,6],[7,8,9]]


In [4]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.zeros((3,3))-2


array([[-2., -2., -2.],
       [-2., -2., -2.],
       [-2., -2., -2.]])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
np.arange(10) #create array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(50).reshape(5,10) #create 2d array


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [11]:
np.linspace(0,10,5)  #linear array method

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
x = np.array(x) #find min max in array

In [13]:
x.max()

5

In [14]:
np.random.rand(5)     #random value

array([0.90466088, 0.0419062 , 0.21570464, 0.99040085, 0.67863975])

In [15]:
np.random.randint(4)

3

In [16]:
x.argmax()  #find max value index number

4

In [17]:
x.argmin()   #find min value index number

0