In [4]:
import numpy as np

In [3]:
x=np.arange(10)

In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y=np.arange(10, 20)

In [6]:
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [23]:
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
z.max()

28

In [40]:
a = np.arange(20).reshape(4,5)

In [41]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
b =np.arange(20,40).reshape(4,5)

In [54]:
b

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [55]:
c=a+b

In [56]:
c

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [59]:
a>b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [51]:
c

[array([], dtype=bool)]

In [61]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])