In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5,5)

In [3]:
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
x[3][2] #access value in row number 3 and column 2

17

In [5]:
x[3,2]

17

In [6]:
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [7]:
x[1:3,1:3]


array([[ 6,  7],
       [11, 12]])

In [8]:
x[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
y = np.arange(1,25)

In [10]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
y>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [12]:
y[y<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
y=20

In [16]:
y


20